version: '3'

services:
  app:
    image: pkufashuo400/peatio
    volumes:
      - ./config:/peatio/config
    command: bash /entrypoint.sh
    links:
      - redis
      - bitcoind
    ports:
      - "3000:3000"

  redis:
    image: redis
    ports:
      - "6379:6379"

  bitcoind:
    image: freewil/bitcoin-testnet-box
    ports:
      - "19001:19001"
      - "19011:19011"
