version: '3'

services:
  app:
    image: pkufashuo400/peatio
    volumes:
      - ./config:/peatio/config
      - ./db:/peatio/db
    command: bash /entrypoint.sh
    links:
      - redis
      - bitcoind
    ports:
      - "3000:3000"

  redis:
    image: redis
    ports:
      - "6379:6379"

  bitcoind:
    image: freewil/bitcoin-testnet-box
    volumes:
      - ./docker-bitcoind.sh:/home/tester/bitcoin-testnet-box/docker-bitcoind.sh
    entrypoint: /home/tester/bitcoin-testnet-box/docker-bitcoind.sh
    ports:
      - "19001:19001"
      - "19011:19011"
