version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/peatio
    command: bash /entrypoint.sh
    ports:
      - "3000:3000"

  db:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"

  redis:
    image: redis
    ports:
      - "6379:6379"

  bitcoind:
    image: freewil/bitcoin-testnet-box
    ports:
      - "19001:19001"
      - "19011:19011"
